### DISCUSSION TITLE
Duplicated messages with `spring.kafka.streams.properties.processing.guarantee: exactly_once_v2`

### DISCUSSION THREAD

**Discussion by oleksii-suprun** [spring-projects/spring-kafka#2663] [Q&A]
Hi All.

Recently I noticed suspicious behavior in my Kafka Streams application. My application reads messages from multiple input topics, extracts some fields from the input message and pushes results to a single output topic. My application configuration is the following:
```
spring:
  application:
    name: my-app-kstreams
  main:
    banner-mode: off
  kafka:
    bootstrap-servers:
      - XXX.XXX.XXX.XXX:9092
    consumer:
      properties:
        spring.json.trusted.packages: com.example.*
    producer:
      properties:
        spring.json.add.type.headers: false
    streams:
      application-id: ${spring.application.name}
      properties:
        topology.optimization: all
        processing.guarantee: exactly_once_v2
        compression.type: gzip
        auto.offset.reset: latest
        default:
          key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
```

But during the QA process, I found that the application produces duplicates in the output topic. I can see the same message with a different offset in the Kafka topic despite the `exactly_once_v2` configuration. I've also verified input topics and have not found any duplicates there.

Does anyone have any advice on what is wrong?
