### ISSUE TITLE
`spring.kafka.jaas.enabled` not working

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [spring-projects/spring-kafka#1279]
Poor english...
I write a demo for writing text to kafka under kerberos.
I try to use yml configuration instead jaas file.
But it seem not working.
Here is my code.
```yml
spring:
  kafka:
    bootstrap-servers: h3a1.ecloud.com:9092
    jaas:
      enabled: true
      options:
        useKeyTab: true
        keyTab: /etc/security/keytabs/iap.app.keytab
        storeKey: true
        useTicketCache: false
        serviceName: kafka
        principal: iap/h3a1.ecloud.com@ECLOUD.COM
      control-flag: required
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: GSSAPI
        kerberos:
          service:
            name: kafka
```
A simple producer for gathering partition info.
```
package com.lanyuan.sender;

import org.springframework.kafka.annotation.EnableKafka;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;

/**
 * Kafak生产者
 *
 * @author ZhangJiacheng
 * @date 2019-08-11
 */
@Component
@EnableKafka
public class KafkaUtils {

    @Resource
    private KafkaTemplate<String, String> kafkaTemplate;

    @PostConstruct
    public void initial() {
        doSomething();
    }

    public void doSomething() {
        kafkaTemplate.partitionsFor("testTopic").forEach(partitionInfo -> System.out.println(partitionInfo.partition()));
    }

}
```
But it throw a exception "**Caused by: java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set**"
I try to debug the `org.springframework.kafka.security.jaas.KafkaJaasLoginModuleInitializer`, but it seem that not be initialized by spring.

Version:
1. Oracle JDK8
2. Spring Boot Starter Parent 2.1.7 RELEASE
