### ISSUE TITLE
spring kafka config in bootstrap.yml can not work

### ISSUE THREAD

**Issue by yaodwwy** [spring-projects/spring-kafka#1297]
🐞 Bug report
spring kafka config bootstrap.yml not work.
```
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: '*'
```
spring.kafka.producer.key-serializer in bootstrap.yml was not work.
