### ISSUE TITLE
Spring Kafka does not read configuration properties as expected

### ISSUE THREAD

**Issue by sigand** [spring-projects/spring-kafka#1439]
springBootVersion = '2.2.6.RELEASE'
springKafkaVersion= '2.4.5.RELEASE'
kafkaVersion = '2.4.1'

Based on the properties that seem to be available in org.springframework.boot.autoconfigure.kafka.KafkaProperties, some properties are not set as expected.

Specifically:
* clientId (both consumer and general)
* consumer.auto-offset-reset
* consumer.ssl
* properties (anywhere)

Config excerpt
```
spring:
  kafka:
    consumer:
      client-id: "client"
      group-id: "group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      max-poll-records: 100
    ssl:
      trust-store-location: "/some/path"
      trust-store-password: "the pwd here"
    bootstrap-servers:
     - http://localhost:9092
    properties:
      request.timeout.ms: 20000
      sasl.mechanism:  "SCRAM-SHA-512"
```
