### ISSUE TITLE
Spring Boot AutoConfiguration not working with "acks" value as "all"

### ISSUE THREAD

**Issue by dilipsundarraj1** [spring-projects/spring-kafka#1526]
**Affects Version(s):** \<Spring for Apache Kafka version>

Hi All,

**Issue**
Spring boot AutoConfiguration does not map the `acks:all` value to the Kafka template.

- It always map the acks value to **-1** when the supply the value as `acks:all` in the **application.yml**

Below is the **application.yml** file that I am using to autoconfigure the KafkaTemplate.

```
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        retries: 10
        retry.backoff.ms: 1000
        acks: all
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094

```

I ran in to this issue with the recent version of SpringBoot and Spring Kafka

Here is the Spring Boot Version that I am using to test this

```
plugins {
	id 'org.springframework.boot' version '2.3.1.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'java'
}

```
Repo : https://github.com/dilipsundarraj1/kafka-for-developers-using-spring-boot/tree/master/library-events-producer

**application.yml** : https://github.com/dilipsundarraj1/kafka-for-developers-using-spring-boot/blob/master/library-events-producer/src/main/resources/application.yml
