### ISSUE TITLE
Spring transaction not rollback when open kafka transaction 

### ISSUE THREAD

**Issue by toby1024** [spring-projects/spring-kafka#1533]
English is not my first language，if you don't see what I am talking ,please tell me.

version: spring-kafka:2.1.12.release, springboot:2.1.14.release.
problem： when I use config transaction-id-prefix， it will stop spring transaction rollback, and it work ok when remove "transaction-id-prefix","retries" configuration.
config:
```yml
spring:
    kafka:
      bootstrap-servers: {server}
      producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.use.type.headers: false

        transaction-id-prefix: {transaction_id}
        retries: 3
```
spring transation code
```java
@Transactional(rollbackFor = Exception.class)
public void doSomeThing(
//do some thing

    throw new Exception();
}
```
