### ISSUE TITLE
kafka stream error

### ISSUE THREAD

**Issue by tojainesh** [spring-projects/spring-kafka#1541]
Hello,
I am working on my first spring kafka stream project. I am trying to build a stream processor. 
I am using spring boot 2.3.1.RELEASE.

While starting an application I am getting below error 
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultKafkaStreamsBuilder' defined in class path resource [org/springframework/kafka/annotation/KafkaStreamsDefaultConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.kafka.config.StreamsBuilderFactoryBean]: Factory method 'defaultKafkaStreamsBuilder' threw exception; nested exception is java.lang.NullPointerException
```

This is how my Kafka stream processor class looks

```
@Configuration
@EnableKafka
@EnableKafkaStreams
public class KafkaStreamProcessor {

    @Bean(name = KafkaStreamsDefaultConfiguration.DEFAULT_STREAMS_CONFIG_BEAN_NAME)
    public KafkaStreamsConfiguration config(KafkaProperties kafkaProperties) {
        Map<String, Object> config = new HashMap<>();
        config.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, kafkaProperties.getBootstrapServers());
        config.put((StreamsConfig.APPLICATION_ID_CONFIG), kafkaProperties.getClientId());
        config.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass());
        config.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, Serdes.Long().getClass());
        return new KafkaStreamsConfiguration(config);
    }

    @Bean
    public KStream<String, Long> kStream(StreamsBuilder kStreamBuilder) {
        Predicate<String, Long> isEven = (k, v) -> v % 2 == 0;
        KStream<String, Long> stream = kStreamBuilder.stream("producer-topic");

        stream.filter(isEven)
                .mapValues(v -> {
                    System.out.println("Processing  " + v);
                    return v;
                })
                .to("stream-output-topic");
        return stream;
    } 
```

application.properties file
```yaml
spring:
  kafka:
    client-id: stream-processor
    bootstrap-servers:
      localhost:9091
    template:
      default-topic: producer-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.LongSerializer
    stream-output-topic: stream-output-topic
```
pom.xml

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.1.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>com.modi</groupId>
	<artifactId>kafka-stream</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>kafka-stream</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-streams</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>
