### ISSUE TITLE
Subclass of ErrorHandlingDeserializer not detected (inconsostent behaviour)

### ISSUE THREAD

**Issue by PhilippMT** [spring-projects/spring-kafka#1565]
Hi all,

I am not sure if this is a bug or the expected behaviour but it might be a bug in my eyes. We want to use the ErrorHandlingDeserializer to catch DeserialzationExceptions. But as we are using the same setup in many applications I wrote a CustomDeserialzer which has the ErrorHandlingDeseralzer as Super-Class and just adds some config options.

```java
public class CustomDeserialzer<T> extends ErrorHandlingDeserializer<T> {
	
	@Override
	public void configure(Map<String, ? extends Object> configs, boolean isKey) {
		Map<String, Object> tmp = new HashMap<>(configs);
		
		tmp.put(ErrorHandlingDeserializer.KEY_DESERIALIZER_CLASS, String.class.getName());
		tmp.put(ErrorHandlingDeserializer.VALUE_DESERIALIZER_CLASS, JsonDeserializer.class.getName());
		tmp.put(JsonDeserializer.VALUE_DEFAULT_TYPE, Name.class.getName());
		
		super.configure(tmp, isKey);
	}

}
```

I set the CustomDeserialzer as `value.deserializer` in the following `application.yaml`.

```yaml
spring.cloud:
  stream:
    function.definition: process
    bindings:
      process-in-0:
        destination: topic1
        group: group1
        consumer:
          useNativeDecoding: true
    kafka:
      binder:
        autoCreateTopics: true
      bindings:
        process-in-0:
          consumer:
            autoCommitOnError: true
            enableDlq: true
            dlqName: dead-out
            configuration:
              value.deserializer: com.example.demo.serde.CustomDeserialzer
```

The `KafkaMessageListenerContainer` uses the method `checkDeserializer` (see referenced Code below) to check if the Deserialzer is Type of `ErrorHandlingDeserializer`. Only in case of `true`, the `KafkaMessageListenerContainer` checks for an Deserialzation-Exception in the Header. But this is not happening in our case.

https://github.com/spring-projects/spring-kafka/blob/9776c42b40fa4fbeae6309336f82a1a5e722a914/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L918-L922

If the `deser` parameter is instanceof `Class`, the check `ErrorHandlingDeserializer.class.isAssignableFrom((Class<?>) deser)` will returne true, if the `deser` object is a Sub-Class of the `ErrorHandlingDeserialzer`.
But the `value.deserializer: com.example.demo.serde.CustomDeserialzer` is not passed as `Class` but as String. But the check `deser.equals(ErrorHandlingDeserializer.class.getName())` will NOT return true, in case of a Deserialzer which uses the `ErrorHandlingDeserializer` as Super-Class.

It looks like the method is inconsostent because handing parameter "com.example.demo.serde.CustomDeserialzer" as String the return value will be `false` and handing the CustomDeserialzer as `Class<?>` the return value is true.
 
A possible solution would be to get a Class-Object with `Class.forName(deser)` and also check with `ErrorHandlingDeserializer.class.isAssignableFrom` on that object like below

```java
private boolean checkDeserializer(Object deser) {
			return deser instanceof Class
					? ErrorHandlingDeserializer.class.isAssignableFrom((Class<?>) deser)
					: deser instanceof String && ErrorHandlingDeserializer.class.isAssignableFrom(Class.forName(deser));
		}
```

Best regards
Philipp
