### ISSUE TITLE
Failed to construct a kafka producer when it tries to serialize a data class using JsonSerializer

### ISSUE THREAD

**Issue by douglas-DS** [spring-projects/spring-kafka#1885]
**Affects Version(s):** 2.5.3

When a producer tries to serialize a value(data class) the application raises a `org.apache.kafka.common.KafkaException` caused by `java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JavaType`

The producer `value-serializer` was configured to use the `org.springframework.kafka.support.serializer.JsonSerializer` class.

It's how my current yaml file looks like:

```
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
```

**Workaround**

To solve this problem i had to put an explicit dependency declaration for `jackson-databind`, as shown below:
```
implementation("com.fasterxml.jackson.core:jackson-databind")
```
