### ISSUE TITLE
Transactions for KafkaTemplate not working every time

### ISSUE THREAD

**Issue by gstaykov** [spring-projects/spring-kafka#2397]
version: 2.8.8 (inherited from spring-boot 2.7.3)
repo with an example that reproduces the bug: https://github.com/gstaykov/spring-kafka-transactional-bug

**Description**

Use case:

I have a rest request that persists something in DB and after that sends kafka message. I want this operation to be transactional. If something fails I want to rollback both the DB insert and the kafka message. 

My code is this:
```
    @GetMapping("/test")
    @Transactional
    public void asd()
    {
        accountRepository.insert();

        kafkaTemplateTransactional.send(topicName, "example message");

        throw new RuntimeException("Ops");
    }
```

Configuration (I'm following this example from the docs: https://docs.spring.io/spring-kafka/reference/html/#ex-jdbc-sync):
```
@Configuration
public class Config
{
    // Create datasource transaction manager so it can chain with kafka transaction manager. Following this documentation: https://docs.spring.io/spring-kafka/reference/html/#ex-jdbc-sync
    @Bean
    @Primary
    public DataSourceTransactionManager dataSourceTransactionManager(DataSource dataSource)
    {
        return new DataSourceTransactionManager(dataSource);
    }

    @Bean
    public KafkaTemplate<String, String> kafkaTemplateTransactional(@Value("${kafka.bootstrap-servers}") String bootstrapServers)
    {
        Map<String, Object> props = new HashMap<>();
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        props.put(ProducerConfig.ACKS_CONFIG, "all");
        props.put(ProducerConfig.COMPRESSION_TYPE_CONFIG, "lz4");
        props.put(ProducerConfig.TRANSACTIONAL_ID_CONFIG, "transaction-id-example"); // enable transaction awareness

        ProducerFactory<String, String> producerFactory = new DefaultKafkaProducerFactory<>(props);

        return new KafkaTemplate<>(producerFactory);
    }

    @Bean
    public NewTopic createTopic(@Value("${kafka.topicName}") String topicName)
    {
        return TopicBuilder.name(topicName)
                           .build();
    }
}
```

If I call this method once every second everything works as expected - I can't see records in DB and Kafka. But if I put some load on this method (start calling it >10 times per second)  I'm starting to see some (not all) messages in Kafka (everything in the DB looks fine).  

**Expected behavior**

I expect to see no messages in Kafka and no records in the DB. 

**Actual behavior**

I can see some messages (not all) in Kafka and no records in the DB.

**Sample**

I have create a project that reproduce the problem for you: https://github.com/gstaykov/spring-kafka-transactional-bug 
In the README you can find info for the setup. It is a super simple project. However, if you need help message me.

**Comment by garyrussell** [comment]
I will take a look next week.

Two things…

1. Is your consumer configured with read_committed isolation.level?
2. Unrelated, but the producer factory should itself be declared as a bean rather than in the template definition.

**Comment by garyrussell** [comment]
Also, you van see transaction activity using DEBUG logging for o.s.kafka and o.s.transaction

**Comment by gstaykov** [comment]
I don't have a consumer in this application. My use case is
1. Receive rest request
2. Persist in DB
3. Send Kafka message 


I'm using kafka-ui (https://github.com/provectus/kafka-ui) to inspect the messages in the topic and I'm not sure what configuration they are using. I'm very confused because everything works as expected until I start stress testing it. I don't think that this inconsistent behavior is due to consumer config.

**Comment by gstaykov** [comment]
I'm sharing my local environment setup as I'm running kafka & kafka-ui in docker. This is the docker-compose that I'm using:

```
version: "3.1"
services:
  kafka:
    image: blacktop/kafka
    ports:
      - 2181:2181
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9093
      - KAFKA_BROKER_ID=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9999:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=kafka:2181
    links:
      - kafka
```
