### ISSUE TITLE
Project cannot be started

### ISSUE THREAD

**Issue by 17734671027** [spring-projects/spring-kafka#2676]
```xml
   <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
        </dependency>
```
definition will report errors if multiple definitions are used because this version cannot setdifinition
```yaml
spring:
  cloud:
    stream:
      definition: process,process1
      function:
        definition: process;process1
        bindings:
          process-in-0:
            consumer:
              concurrency: 1
              maxAttempts: 1
            destination: words
          process-out-0:
            destination: counts
          process1-in-0:
            group: anotherGroup
            consumer:
              concurrency: 1
              maxAttempts: 1
            destination: counts
```

```java
private void addResolvableTypeInfo(String key, ResolvableType resolvableType) {
		if (kafkaStreamsOnlyResolvableTypes.size() == 1) {
			resolvableTypeMap.put(key, resolvableType);
		}
		else {
			final String definition = streamFunctionProperties.getDefinition();
			if (definition == null) {
				throw new IllegalStateException("Multiple functions found, but function definition property is not set.");
			}
			else if (definition.contains(key)) {
				resolvableTypeMap.put(key, resolvableType);
			}
		}
	}
```
But properties cannot be injected because there is no setdifinition method

```java
@ConfigurationProperties("spring.cloud.stream.function")
public class StreamFunctionConfigurationProperties {
	private Map<String, String> bindings = new HashMap<>();

	public Map<String, String> getBindings() {
		return this.bindings;
	}

	public void setBindings(Map<String, String> bindings) {
		this.bindings = bindings;
	}
}
```
