### ISSUE TITLE
Custom micrometer tags are not displayer on actuator/prometheus page.

### ISSUE THREAD

**Issue by tbarabanov** [spring-projects/spring-kafka#3070]
**spring-kafka version** 
org.springframework.kafka:spring-kafka:jar:3.0.10

**micrometer version**
io.micrometer:micrometer-core:jar:1.11.3
io.micrometer:micrometer-registry-prometheus:jar:1.11.3
io.micrometer:micrometer-observation:jar:1.11.3

**Custom micrometer tags are not displayer on `actuator/prometheus` page.**

I'm using autoconfigured kafka with a simple listener:

```yaml
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: 'some.value'
      enable-auto-commit: false
      auto-offset-reset: latest
      max-poll-records: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
```

```java
@KafkaListener(topics = "pike")
public void listen(ConsumerRecord<String, String> record) {
    System.out.println(record.topic());
}
```

```java
@Bean
DefaultKafkaConsumerFactoryCustomizer kafkaConsumerFactoryCustomizer(MeterRegistry meterRegistry) {
    return consumerFactory -> consumerFactory.addListener(
        new MicrometerConsumerListener<>(meterRegistry));
}
```

```java
@Component
class ConcurrentKafkaListenerContainerFactoryCustomizer {

    // autoconfigured kafkaListenerContainerFactory customizer
    public ConcurrentKafkaListenerContainerFactoryCustomizer(
        ConcurrentKafkaListenerContainerFactory<?, ?> kafkaListenerContainerFactory,
        Function<ConsumerRecord<?, ?>, Map<String, String>> micrometerTagsProvider) {
      kafkaListenerContainerFactory.setContainerCustomizer(
          container -> {
            container.getContainerProperties().setMicrometerTagsProvider(micrometerTagsProvider);
          });
    }
  }
```

In IDE debug I see that my micrometerTagsProvider gets called (tags are generated) as well as the code in `MicrometerHolder.java` 
```java
private Timer buildTimer(String exception, @Nullable Object record) {
		Builder builder = Timer.builder(this.timerName)
			.description(this.timerDesc)
			.tag("name", this.name)
			.tag("result", exception.equals(NONE_EXCEPTION_METERS_KEY) ? "success" : "failure")
			.tag("exception", exception);
		Map<String, String> extra = this.tagsProvider.apply(record);
		if (extra != null && !extra.isEmpty()) {
			extra.forEach(builder::tag);
		}
		Timer registeredTimer = builder.register(this.registry);
		if (record == null) {
			this.meters.put(exception, registeredTimer);
		}
		return registeredTimer;
	}
```

I see that custom tags are added to builder, I see `spring.kafka.listener` metrics on `actuator/prometheus` page but no custom tags are displayed.

**expected result**
custom tags must be displayed on `actuator/prometheus` page along with their metrics
