### ISSUE TITLE
Creation of `kafkaJaasInitializer` bean fails in a read-only filesystem due to creation of temporary file 

### ISSUE THREAD

**Issue by FieteO** [spring-projects/spring-kafka#3217]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**
3.1.2

**Describe the bug**

I have a spring app that is running in a Kubernetes cluster. To comply to security policies, the filesystem of the pod has to be switched to read-only (`securityContext.readOnlyRootFilesystem: true`).
However this is currently not possible because the app is crashing due to spring-kafka (as far as I can tell).

Here is a stack-trace:
```sh
{"@timestamp":"2024-04-25T07:15:57.209724778Z","@version":"1","message":"Application run failed","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","level":"ERROR","level_value":40000,"stack_trace":"org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaJaasInitializer' defined in class path resource [org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.class]: Failed to instantiate [org.springframework.kafka.security.jaas.KafkaJaasLoginModuleInitializer]: Factory method 'kafkaJaasInitializer' threw exception with message: Read-only file system\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1335)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1165)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)\n\tat org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)\n\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)\n\tat org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962)\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)\n\tat org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:334)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)\n\tat de.telekom.tnap.portal.bff.Application.main(Application.java:39)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)\n\tat org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)\n\tat org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.kafka.security.jaas.KafkaJaasLoginModuleInitializer]: Factory method 'kafkaJaasInitializer' threw exception with message: Read-only file system\n\tat org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)\n\t... 26 common frames omitted\nCaused by: java.io.IOException: Read-only file system\n\tat java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)\n\tat java.base/java.io.File.createTempFile(File.java:2170)\n\tat java.base/java.io.File.createTempFile(File.java:2216)\n\tat org.springframework.kafka.security.jaas.KafkaJaasLoginModuleInitializer.<init>(KafkaJaasLoginModuleInitializer.java:102)\n\tat org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration.kafkaJaasInitializer(KafkaAutoConfiguration.java:148)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)\n\t... 27 common frames omitted\n"}
```
It seems the issue is related to the fact that spring-kafka is creating a temporary file during it's initialization.

**To Reproduce**
Have a spring-boot app on the latest `3.2.5` release and spring-kafka. The following `application.yml` is used:
```yaml
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      ack-mode: manual_immediate
    consumer:
      group-id: mygroup
      max-poll-records: 1000
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      isolation-level: read_committed
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: ${KAFKA_SASL_JAAS_CONFIG}
```
With `${KAFKA_SASL_JAAS_CONFIG}` being:
```
org.apache.kafka.common.security.scram.ScramLoginModule required username="strimzi-kafka-admin" password="somePassword";
```

**Expected behavior**

That spring-kafka can be run with a read-only filesystem by not creating temporary files in the background.

**Comment by FieteO** [comment]
## Workaround:
`createTempFile()` will create a file in `/tmp` with a partially random name:
```
$ ls -lh /tmp/ | grep kafka-client
-rw-r--r-- 1 ubuntu ubuntu    0 Apr 25 10:22 kafka-client-jaas-config-placeholder13695674278614452518conf
```
As such, it's necessary to mount the whole `tmp` directory as a volume in Kubernetes:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      ...
      containers:
        - name: {{ .Chart.Name }}
          image: ...
          ...
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      ...
      volumes:
        - name: tmp-volume
          emptyDir:
            sizeLimit: 64Mi
```
This way it working, but it would be great if that additional step wouldn't be necessary
