### ISSUE TITLE
The parameter consumer.auto-commit-interval does not work

### ISSUE THREAD

**Issue by georgege08** [spring-projects/spring-kafka#3394]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.2.2

springboot 3.3.2

**Describe the bug**

consumer.auto-commit-interval does not work

**To Reproduce**

application.yaml
`
spring:
  application:
    name: TestSpringKafka2

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties: 
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: true
      auto-commit-interval: 20000
`

User.java
`
@Getter
@Setter
public class User {
    private String firstName;
    private String lastName;
    private int age;

    @Override
    public String toString() {
        return "User{" +
                "firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", age=" + age +
                '}';
    }
}
`

TestSpringKafka2ApplicationTests.java
`
@SpringBootTest
class TestSpringKafka2ApplicationTests {

    @Resource
    KafkaTemplate<String, User> kafkaTemplate;

    @Test
    void testProducer() {
        User user = new User();
        user.setAge(21);
        user.setFirstName("jerry");
        user.setLastName("wade");
        kafkaTemplate.send("abc",user);
    }

}
`

TestConsumer.java
`
@Component
public class TestConsumer {

    @KafkaListener(topics = "abc" , groupId = "consumer-group-100")
    public void dealUser(User user) {
        System.out.println(user.toString());
    }
}
`

The printed consumer config values:
`
	allow.auto.create.topics = true
	auto.commit.interval.ms = 20000
	auto.include.jmx.reporter = true
	auto.offset.reset = latest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.dns.lookup = use_all_dns_ips
	client.id = consumer-consumer-group-100-1
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = true
	enable.metrics.push = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = consumer-group-100
	group.instance.id = null
	group.protocol = classic
	group.remote.assignor = null
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	internal.throw.on.fetch.stable.offset.unsupported = false
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor, class org.apache.kafka.clients.consumer.CooperativeStickyAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.max.ms = 1000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = GSSAPI
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	session.timeout.ms = 45000
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.springframework.kafka.support.serializer.JsonDeserializer
`

**Expected behavior**

when I call the testProducer method, I except the consumer current-offset will not increase immediately, as I've set the auto-commit-interval to 20000(20 seconds), while actually, I found it added to 1 immediately

```
./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group consumer-group-100
GROUP              TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                        HOST            CLIENT-ID
consumer-group-100 abc             0          1               1               0               consumer-consumer-group-100-1-26560125-1b4d-4836-bdf2-9b7e4b21a68a /172.23.0.1     consumer-consumer-group-100-1
```

**Comment by sobychacko** [comment]
@georgege08 Looks like the properties are set properly - `enable.auto.commit` to true and the interval property. Is there any chance you can put this together in a small reproducible sample app? That way it is easier for us to triage further.

**Comment by sobychacko** [comment]
I wonder if this is a timing issue on your application's end. I created a sample app from your configs and increased the `auto.commit.interval` value to `60_000` to see if there is any difference. After publishing the record, I see the offsets are not yet committed, but after a minute, they are updated.  Here is what I am seeing. 
```
./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group consumer-group-100

GROUP              TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                        HOST            CLIENT-ID
consumer-group-100 abc             0          -               1               -               consumer-consumer-group-100-1-9c60b631-2dee-44be-a217-76b769bdd6c0 /172.18.0.1     consumer-consumer-group-100-1


After a minute

./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group consumer-group-100

GROUP              TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                        HOST            CLIENT-ID
consumer-group-100 abc             0          1               1               0               consumer-consumer-group-100-1-9c60b631-2dee-44be-a217-76b769bdd6c0 /172.18.0.1     consumer-consumer-group-100-1
```

I see it also works correctly for `auto.commit.interval` set to `20_000`. 

This tells me that things are working as expected. Could you try this on your end and verify?

**Comment by georgege08** [comment]
@sobychacko Yes, I had tried many times, whatever the auto.commit.interval set to, the CURRENT-OFFSET will increase immediately, the attachment is my whole project, please help to check it.
[TestSpringKafka2.zip](https://github.com/user-attachments/files/16420500/TestSpringKafka2.zip)

btw:
The kafka server is built on my local environment with docker, this is the docker-compose.yaml

```
version: "2.5"
volumes:
  volume1:
services:
  kafka1:
    image: 'bitnami/kafka:3.6.2'
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.110.36:9092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    volumes:
      - volume1:/bitnami/kafka
    ports:
      - "9092:9092"
  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - "8055:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
      - KAFKA_CLUSTERS_0_NAME=r4zt_wrqTRuT7W2NJsB_GA
```

and I enter the container to check the consumer offset with:
```
(base) gejing@GedeMacBook-Pro kafka % docker exec -it 8d81380226ba /bin/bash
I have no name!@8d81380226ba:/$ cd /opt/bitnami/kafka/bin/
I have no name!@8d81380226ba:/opt/bitnami/kafka/bin$ ./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group consumer-group-100

GROUP              TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                        HOST            CLIENT-ID
consumer-group-100 abc             0          1               1               0               consumer-consumer-group-100-1-5d3c03e4-a268-474b-b945-0703d87eb602 /172.24.0.1     consumer-consumer-group-100-1
I have no name!@8d81380226ba:/opt/bitnami/kafka/bin$ 
I have no name!@8d81380226ba:/opt/bitnami/kafka/bin$ 
I have no name!@8d81380226ba:/opt/bitnami/kafka/bin$ ./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group consumer-group-100

GROUP              TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                        HOST            CLIENT-ID
consumer-group-100 abc             0          2               2               0               consumer-consumer-group-100-1-5d3c03e4-a268-474b-b945-0703d87eb602 /172.24.0.1     consumer-consumer-group-100-1
```
I'm not sure if this environment has any impact on the current-offset value.

**Comment by sobychacko** [comment]
@georgege08 Can you do the following experiment, as I cannot reproduce this issue locally? Take the following application.
```
@SpringBootApplication
public class Gh3394Application {

	public static void main(String[] args) {
		SpringApplication.run(Gh3394Application.class, args);
	}

	@Bean
	public ApplicationRunner runner(KafkaTemplate<String, Object> kafkaTemplate) {
		return args -> {
			User user = new User("Foo", "Bar", 21);
			kafkaTemplate.send("abc",user);
		};
	}

	@Component
	static class Listener {

		@KafkaListener(topics = "abc" , groupId = "consumer-group-100")
		public void dealUser(User user) {
			System.out.println(user.toString());
		}
	}

	record User(String firstName, String lastName, int age) {}
}

```

config:

```
spring:
  application:
    name: TestSpringKafka2
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: true
      auto-commit-interval: 60000
```
Run the app against a local Kafka cluster (not the one based on your docker).

Then, execute the shell script to track the consumer group.

Observe if you see any issues. 

If not, then change the Kafka cluster to the one based on Bitnami (docker based).

If there are issues, then you know where the problem is. 

Please let us know how that goes. 

Thanks!
