### ISSUE TITLE
how to config request.timeout.ms

### ISSUE THREAD

**Issue by freeFeatrue** [spring-projects/spring-kafka#510]
KafkaProperties.java restricts only a few configurations, how to config request.timeout.ms ???

**Comment by nklmish** [comment]
KafkaProperties allows access to other properties via `properties`, you can use it like this:
```
spring:
  kafka:
      properties:
        request.timeout.ms: 100
```
